openapi: 3.0.0
info:
  title: Registrations API
  version: 1.0.0
  description: API documentation for managing registrations.

paths:
  /registrations:
    get:
      summary: Get all registrations
      operationId: getAllRegistrations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registration'
    post:
      summary: Create a new registration
      operationId: createRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'

  /registrations/{id}:
    get:
      summary: Get a registration by ID
      operationId: getRegistrationById
      parameters:
        - name: id
          in: path
          description: ID of the registration to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
    put:
      summary: Update a registration by ID
      operationId: updateRegistration
      parameters:
        - name: id
          in: path
          description: ID of the registration to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
    delete:
      summary: Delete a registration by ID
      operationId: deleteRegistration
      parameters:
        - name: id
          in: path
          description: ID of the registration to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Registration:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        address:
          type: string
        age:
          type: integer
          format: int64
        gender:
          type: string
          enum: ['male', 'female']
        OTP:
          type: integer
          format: int64
        OTP_verify:
          type: string
          enum: ['true', 'false']
      required:
        - first_name
        - last_name
        - address
        - age
        - gender
        - OTP
        - OTP_verify
